#!/usr/bin/env python3
"""Clean Logseq-flavored notes into regular Markdown with YAML frontmatter."""

from __future__ import annotations

import argparse
import re
import sys
from collections import OrderedDict
from datetime import date
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
TODAY = date.today().isoformat()

EXCLUDED_DIRS = {
    ".git",
    ".obsidian",
    ".venv",
    "__pycache__",
    "config",
    "graphify-out",
    "logseq",
    "node_modules",
}

EXCLUDED_ROOT_FILES = {
    "AGENTS.md",
    "RULES.md",
    "Readme.md",
}

PROPERTY_RE = re.compile(
    r"^[ \t]*(?:collapsed|id|created-at|updated-at|background-color|heading|ls-type)::\s*.*$"
)
LIST_RE = re.compile(r"^([ \t]*)([-*])\s+(.*)$")
EMPTY_LIST_RE = re.compile(r"^[ \t]*[-*]\s*$")
HEADING_RE = re.compile(r"^(#{1,6})\s+(.+)$")
ORDERED_RE = re.compile(r"^\d+\.\s+")
TASK_RE = re.compile(r"^\[[ xX]\]\s+")
WIKILINK_RE = re.compile(r"\[\[([^\]|#]+)(?:#[^\]|]+)?(?:\|[^\]]+)?\]\]")
INLINE_TAG_RE = re.compile(r"(?<![\w/])#([A-Za-z][A-Za-z0-9_/-]*)")
FRONTMATTER_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*:")
FOAM_LINK_BLOCK_RE = re.compile(
    r"(?ms)^[ \t]*\[//begin\]: # \"Autogenerated link references for markdown compatibility\".*?"
    r"^[ \t]*\[//end\]: # \"Autogenerated link references\"[ \t]*\n?"
)
MARKDOWN_ANGLE_LINK_RE = re.compile(r"\[([^\]]+)\]<((?:https?|file)://[^>]+)>")
LOGSEQ_PAGE_EMBED_RE = re.compile(
    r"`*\{\{embed\s+\[\[([^\]]+)\]\]\s*`*\}\}`*|`*\{\{embed\s+\[\[([^\]]+)\]\]\s*`*\}*`*"
)
LOGSEQ_BLOCK_EMBED_RE = re.compile(
    r"`*\{\{embed\s+\(\(([0-9A-Za-z_-]+(?:-[0-9A-Za-z_-]+)*)\)\)\s*`*\}\}`*|"
    r"`*\{\{embed\s+\(\(([0-9A-Za-z_-]+(?:-[0-9A-Za-z_-]+)*)\)\)\s*`*\}*`*"
)
YOUTUBE_TS_RE = re.compile(r"`*\{\{youtube-timestamp\s+([^}`]+)(?:`([^}]+))?\}\}`*")
CODE_FENCE_RE = re.compile(r"^[ \t]*(```|~~~)")


def target_files() -> list[Path]:
    files: list[Path] = []
    for path in ROOT.rglob("*.md"):
        rel = path.relative_to(ROOT)
        if any(part in EXCLUDED_DIRS for part in rel.parts):
            continue
        if len(rel.parts) == 1 and rel.name in EXCLUDED_ROOT_FILES:
            continue
        files.append(path)
    return sorted(files)


def split_frontmatter(text: str) -> tuple[dict[str, Any], str]:
    if not text.startswith("---\n"):
        return {}, text

    end = text.find("\n---", 4)
    if end == -1:
        return {}, text

    marker_end = text.find("\n", end + 4)
    if marker_end == -1:
        marker_end = len(text)
    raw = text[4:end]
    body = text[marker_end + 1 :]
    try:
        data = yaml.safe_load(raw) or {}
    except yaml.YAMLError:
        data = {}
    if not isinstance(data, dict):
        data = {}
    return data, body


def title_from_filename(path: Path) -> str:
    stem = path.stem.replace("_", " ").strip()
    if re.fullmatch(r"\d{4}_\d{2}_\d{2}", path.stem):
        return path.stem.replace("_", "-")
    return stem or "Untitled"


def first_h1(body: str) -> str | None:
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.startswith("# ") and not stripped.startswith("#["):
            return stripped[2:].strip()
        if stripped:
            break
    return None


def infer_type(path: Path) -> str:
    rel = path.relative_to(ROOT)
    parts = rel.parts
    if parts[:2] == ("content", "domains"):
        return "permanent"
    if parts[:2] == ("content", "people"):
        return "permanent"
    if parts[:2] == ("content", "media"):
        return "literature"
    if parts[:2] == ("content", "research"):
        return "research"
    if parts[:2] == ("content", "journal"):
        return "journal"
    if parts and parts[0] == "journals":
        return "journal"
    return "research"


def infer_category(path: Path) -> str:
    rel = path.relative_to(ROOT)
    parts = rel.parts
    if parts[:2] == ("content", "domains"):
        bits = parts[2:-1]
    elif parts[:2] == ("content", "media"):
        bits = parts[1:-1]
    elif parts[:2] == ("content", "people"):
        bits = ["people"]
    elif parts[:2] == ("content", "research"):
        bits = parts[1:-1] or ["research"]
    elif parts[:2] == ("content", "journal") or (parts and parts[0] == "journals"):
        bits = ["journal"]
    elif parts and parts[0] == "pages":
        bits = ["legacy", "pages"]
    elif len(parts) > 1:
        bits = parts[:-1]
    else:
        bits = ["index"] if rel.name == "INDEX.md" else ["legacy"]
    return "/".join(bit.replace("-", " ").replace("_", " ").title() for bit in bits)


def infer_date(path: Path, frontmatter: dict[str, Any]) -> str:
    existing = frontmatter.get("date")
    if existing:
        return str(existing)
    for candidate in (path.stem, path.name):
        match = re.search(r"(20\d{2})[-_](\d{2})[-_](\d{2})", candidate)
        if match:
            return "-".join(match.groups())
    return TODAY


def normalize_tags(value: Any, body: str) -> list[str]:
    tags: list[str] = []
    if isinstance(value, str):
        tags.extend(split_tag_value(value))
    elif isinstance(value, list):
        for item in value:
            tags.extend(split_tag_value(str(item)))
    elif isinstance(value, dict):
        tags.extend(split_tag_value(" ".join(str(k) for k in value)))

    for tag in INLINE_TAG_RE.findall(body):
        if tag.lower() in {"begin", "end"}:
            continue
        tags.append(tag)

    seen: set[str] = set()
    normalized: list[str] = []
    for tag in tags:
        clean = tag.strip().lstrip("#").replace(" ", "-")
        if not clean:
            continue
        key = clean.lower()
        if key in seen:
            continue
        seen.add(key)
        normalized.append(clean)
    return normalized


def split_tag_value(value: str) -> list[str]:
    value = value.strip()
    if not value:
        return []
    value = value.strip("[]")
    return [part.strip().strip("'\"") for part in re.split(r"[,\s]+", value) if part.strip()]


def related_from_body(body: str, limit: int = 8) -> list[str]:
    links: list[str] = []
    seen: set[str] = set()
    for raw in WIKILINK_RE.findall(body):
        title = raw.strip()
        if not title:
            continue
        key = title.lower()
        if key in seen:
            continue
        seen.add(key)
        links.append(f"[[{title}]]")
        if len(links) >= limit:
            break
    return links


def normalize_related(value: Any, body: str, note_type: str) -> list[str] | None:
    related: list[str] = []
    if isinstance(value, str):
        related.extend(extract_related_strings(value))
    elif isinstance(value, list):
        for item in value:
            related.extend(extract_related_strings(str(item)))
    if not related and note_type == "permanent":
        related = related_from_body(body)
    seen: set[str] = set()
    result: list[str] = []
    for item in related:
        clean = item.strip().strip("'\"")
        if not clean:
            continue
        if clean.startswith("[[") and clean.endswith("]]"):
            normalized = clean
        else:
            normalized = f"[[{clean}]]"
        key = normalized.lower()
        if key in seen:
            continue
        seen.add(key)
        result.append(normalized)
    return result or None


def extract_related_strings(value: str) -> list[str]:
    links = [f"[[{item.strip()}]]" for item in WIKILINK_RE.findall(value)]
    if links:
        return links
    return [part.strip() for part in value.strip("[]").split(",") if part.strip()]


def block_id_map(files: list[Path]) -> dict[str, str]:
    ids: dict[str, str] = {}
    for path in files:
        text = path.read_text(encoding="utf-8", errors="replace")
        _, body = split_frontmatter(text)
        previous = ""
        for raw_line in body.splitlines():
            line = raw_line.rstrip()
            match = re.match(r"^[ \t]*id::\s*([0-9A-Za-z_-]+(?:-[0-9A-Za-z_-]+)*)\s*$", line)
            if match and previous:
                ids[match.group(1)] = title_from_filename(path)
                continue
            if PROPERTY_RE.match(line) or not line.strip():
                continue
            cleaned = LIST_RE.sub(lambda m: m.group(3).strip(), line).strip()
            if cleaned:
                previous = cleaned
    return ids


def normalize_indent(raw: str) -> str:
    level = 0
    spaces = 0
    for char in raw:
        if char == "\t":
            level += 1
        elif char == " ":
            spaces += 1
    level += spaces // 2
    return "  " * level


def clean_inline(text: str, ids: dict[str, str]) -> str:
    text = MARKDOWN_ANGLE_LINK_RE.sub(r"[\1](\2)", text)

    def page_embed(match: re.Match[str]) -> str:
        title = (match.group(1) or match.group(2) or "").strip()
        return f"![[{title}]]" if title else ""

    def block_embed(match: re.Match[str]) -> str:
        block_id = (match.group(1) or match.group(2) or "").strip()
        title = ids.get(block_id)
        return f"![[{title}]]" if title else f"<!-- unresolved Logseq block embed: {block_id} -->"

    def youtube_timestamp(match: re.Match[str]) -> str:
        raw = " ".join(part for part in match.groups() if part).strip()
        raw = raw.replace("`", ":").strip()
        return f"(timestamp {raw})" if raw else ""

    text = LOGSEQ_PAGE_EMBED_RE.sub(page_embed, text)
    text = LOGSEQ_BLOCK_EMBED_RE.sub(block_embed, text)
    text = YOUTUBE_TS_RE.sub(youtube_timestamp, text)
    text = re.sub(r"#\[\[([^\]]+)\]\]", r"[[\1]]", text)
    text = re.sub(r"\s+$", "", text)
    return text


def should_keep_bullet(path: Path, content: str, indent: str) -> bool:
    rel = path.relative_to(ROOT)
    parts = rel.parts
    if TASK_RE.match(content):
        return True
    if ORDERED_RE.match(content):
        return False
    if content.startswith(("[[", "[", "http://", "https://", "#")):
        return True
    if content.startswith("**") and ":" in content[:80]:
        return True
    if content.startswith(("Note:", "Tags:", "Source:", "Author:", "Title:", "Link:", "Host:", "Guest:")):
        return True
    if parts[:3] == ("content", "media", "books") and "highlights" in parts:
        return True
    if parts[:2] == ("content", "research"):
        return True
    if indent:
        return True
    if len(content) <= 90 and not re.search(r"[.!?;:]$", content):
        return True
    return False


def clean_body(path: Path, body: str, ids: dict[str, str]) -> str:
    body = body.replace("\r\n", "\n").replace("\r", "\n").replace("\u00a0", " ")
    body = FOAM_LINK_BLOCK_RE.sub("", body)
    lines = body.splitlines()
    out: list[str] = []
    in_fence = False

    for raw_line in lines:
        if CODE_FENCE_RE.match(raw_line):
            in_fence = not in_fence
            out.append(raw_line.rstrip())
            continue
        if in_fence:
            out.append(raw_line.rstrip())
            continue

        if PROPERTY_RE.match(raw_line):
            continue
        if EMPTY_LIST_RE.match(raw_line):
            out.append("")
            continue

        match = LIST_RE.match(raw_line)
        if match:
            indent = normalize_indent(match.group(1))
            content = clean_inline(match.group(3).strip(), ids)
            if not content:
                out.append("")
                continue
            heading = HEADING_RE.match(content)
            if heading:
                out.append(f"{heading.group(1)} {heading.group(2).strip()}")
                continue
            if ORDERED_RE.match(content):
                out.append(f"{indent}{content}")
                continue
            if should_keep_bullet(path, content, indent):
                out.append(f"{indent}- {content}")
            else:
                out.append(content)
            continue

        line = clean_inline(raw_line.rstrip().replace("\t", "  "), ids)
        if FRONTMATTER_KEY_RE.match(line.strip()) and line.startswith("  "):
            line = line.strip()
        out.append(line)

    return normalize_blank_lines(out)


def normalize_blank_lines(lines: list[str]) -> str:
    result: list[str] = []
    previous_blank = True
    for line in lines:
        stripped = line.rstrip()
        if stripped == "":
            if not previous_blank:
                result.append("")
            previous_blank = True
            continue

        if HEADING_RE.match(stripped):
            if result and result[-1] != "":
                result.append("")
            result.append(stripped)
            previous_blank = False
            continue

        result.append(stripped)
        previous_blank = False

    while result and result[-1] == "":
        result.pop()
    return "\n".join(result) + "\n"


def yaml_scalar(value: Any) -> str:
    if value is None:
        return '""'
    text = str(value)
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def yaml_list(values: list[Any]) -> str:
    if not values:
        return "[]"
    return "[" + ", ".join(yaml_scalar(item) for item in values) + "]"


def render_frontmatter(data: dict[str, Any]) -> str:
    ordered = OrderedDict()
    for key in ("title", "date", "type", "category", "tags", "status", "source", "related"):
        if key in data and data[key] not in (None, ""):
            ordered[key] = data[key]
    for key, value in data.items():
        if key not in ordered:
            ordered[key] = value

    lines = ["---"]
    for key, value in ordered.items():
        if isinstance(value, list):
            lines.append(f"{key}: {yaml_list(value)}")
        elif isinstance(value, bool):
            lines.append(f"{key}: {'true' if value else 'false'}")
        elif isinstance(value, (int, float)):
            lines.append(f"{key}: {value}")
        else:
            lines.append(f"{key}: {yaml_scalar(value)}")
    lines.append("---")
    return "\n".join(lines) + "\n\n"


def ensure_h1(title: str, body: str) -> str:
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if stripped.startswith("# ") and not stripped.startswith("#["):
            return body
        if stripped.startswith("---"):
            return body
        break
    return f"# {title}\n\n{body.lstrip()}"


def clean_file(path: Path, ids: dict[str, str]) -> tuple[str, str]:
    original = path.read_text(encoding="utf-8", errors="replace")
    frontmatter, body = split_frontmatter(original)
    body = clean_body(path, body, ids)
    note_type = str(frontmatter.get("type") or infer_type(path))
    title = str(frontmatter.get("title") or first_h1(body) or title_from_filename(path))

    cleaned_frontmatter: dict[str, Any] = dict(frontmatter)
    cleaned_frontmatter["title"] = title
    cleaned_frontmatter["date"] = infer_date(path, frontmatter)
    cleaned_frontmatter["type"] = note_type
    cleaned_frontmatter["category"] = str(frontmatter.get("category") or infer_category(path))
    cleaned_frontmatter["tags"] = normalize_tags(frontmatter.get("tags"), body)
    cleaned_frontmatter["status"] = str(frontmatter.get("status") or "draft")

    related = normalize_related(frontmatter.get("related"), body, note_type)
    if related:
        cleaned_frontmatter["related"] = related
    elif "related" in cleaned_frontmatter:
        cleaned_frontmatter.pop("related", None)

    body = ensure_h1(title, body)
    cleaned = render_frontmatter(cleaned_frontmatter) + body
    return original, cleaned


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write changes to files")
    args = parser.parse_args()

    files = target_files()
    ids = block_id_map(files)
    changed: list[Path] = []

    for path in files:
        original, cleaned = clean_file(path, ids)
        if original != cleaned:
            changed.append(path)
            if args.write:
                path.write_text(cleaned, encoding="utf-8")

    mode = "updated" if args.write else "would update"
    print(f"{mode} {len(changed)} of {len(files)} note files")
    for path in changed:
        print(path.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
